"""
reports/signal_status.py -- the ONE place signal statuses are classified.

WHY THIS MODULE EXISTS.
`signals.status` is a STRUCTURED field with a known vocabulary. `signals.rejection_reason` is
FREE TEXT: a human sentence that embeds the symbol and the sizing arm values, e.g.

    "qty=0: CONCENTRATION exhausted for GRAVITA (risk_qty=6 capital_qty=17 conc_qty=0)"

Classifying by that free text is the defect this module exists to make impossible. Two live
examples, both measured on production data:

  * `daily_report.py:464` counted a rejection as CAPITAL when the reason string contained
    "CAPITAL" -- which the CONCENTRATION reason does, via `capital_qty=`. On 2026-07-10 that
    reported **1,189 capital rejections when the true count was 0**; all 1,189 were
    CONCENTRATION. The report told the operator the system was capital-starved while the
    constraint that actually binds 100% of the time was never named.
  * `daily_report.py:549` grouped the rejection breakdown by that same free text. Because the
    string embeds the symbol and three numbers, 7,655 rejected signals produced **190 distinct
    breakdown lines** instead of 9 -- each too small to notice, sorted to the bottom.

THE RULE THIS ENCODES: *** classify, count, filter and group by the STRUCTURED status; render
the free text as detail only. *** Displaying `rejection_reason` to a human is correct and
expected (Sheet 1 shows it per signal). Branching on its contents is not.

Prefix matching on `status` is deliberate and safe in a way substring matching on free text is
not: the status vocabulary is generated by the system itself
(`signal_processor.py` raises `_PipelineReject(f"SIZING_{constraint}")` -> `REJECTED_SIZING_*`),
so the families below are contractual, not incidental.

`bucket()` and its two vocabularies moved here from `reports/daily_trade_review.py`, which had
the right pattern already; it now imports from here so there is exactly ONE implementation.
"""
from __future__ import annotations

import re
from typing import Optional

# Statuses meaning "this signal made it through to an order attempt".
QUALIFIED_STATUSES = {"PROCESSED", "TRADED", "PLACEMENT_FAILED", "RESERVED",
                      "PROCESSED_NO_PLACER", "PASSED"}

# Known non-terminal / other statuses. A status outside ALL of {qualified, rejected, skipped,
# dropped, known-other} is 'unmapped' -> it makes the SIGNAL-STORAGE reconciliation delta != 0
# (a real schema-drift alarm, not a silent catch-all).
KNOWN_OTHER_STATUSES = {"EXPIRED", "QUEUE_FULL", "QUEUED", "PENDING", "CANCELLED",
                        "TIMEOUT", "IN_PROCESS", "FAILED", "ACCEPTED", "PROCESSING",
                        "DUPLICATE", "INVALID_SYMBOL", "INVALID_PRICE", "OUTSIDE_HOURS"}

# The score gate emits one status PER SCORE (REJECTED_SCORE_29 ... REJECTED_SCORE_59), which
# fragments a breakdown into ~40 lines. Collapse the family; the individual scores remain
# visible per-signal in the Signals sheet.
_SCORE_STATUS_RE = re.compile(r"^REJECTED_SCORE_\d+$")

# The sizing family, in the order position_sizer.py evaluates them. Used to name WHICH sizing
# constraint bound -- the question the old free-text count got exactly backwards.
SIZING_PREFIX = "REJECTED_SIZING_"

# The risk engine's check 2 is NAMED "SIZING_VALID" (risk_engine.py:407-411 -- sizing_result.success
# must be True); a failure there is emitted as REJECTED_SIZING_VALID. That shares the position_sizer's
# REJECTED_SIZING_ prefix but is NOT a sizer constraint -- it is the risk engine re-validating the
# sizer's success flag one layer later. Excluded from the sizing family below so the sizing-rejection
# count and the named binding constraint stay a position_sizer property, rather than a risk-engine
# outcome mislabelled as constraint "VALID". Latent today (0 such rows) but the prefixes truly collide.
_RISK_ENGINE_SIZING_STATUS = "REJECTED_SIZING_VALID"


def bucket(status: Optional[str]) -> str:
    """Coarse disposition of a signal: qualified / rejected / skipped / dropped / other /
    unmapped. Moved from daily_trade_review._signal_bucket -- same semantics."""
    s = (status or "").upper()
    if s.startswith("REJECTED"):
        return "rejected"
    if s.startswith("SKIPPED_"):
        return "skipped"
    if s.startswith("DROPPED_"):
        return "dropped"
    if s in QUALIFIED_STATUSES:
        return "qualified"
    if s in KNOWN_OTHER_STATUSES or s.startswith("GATE_") or s.startswith("RETEST_"):
        return "other"
    return "unmapped"


def is_rejected(status: Optional[str]) -> bool:
    """True for the REJECTED_* family only.

    NOTE this is narrower than "did not trade": DROPPED_*, SKIPPED_*, QUEUE_FULL,
    PLACEMENT_FAILED and TIMEOUT are also terminal without being REJECTED_*. Use
    `has_explicit_disposition()` when the question is "did this signal die for a KNOWN
    reason" -- conflating the two is what made 2,688 signals look 'silently dead'.
    """
    return bucket(status) == "rejected"


def has_explicit_disposition(status: Optional[str]) -> bool:
    """True when the system recorded a KNOWN outcome for this signal.

    'Silent dead' is meant to mean *we cannot account for this signal at all* -- which is
    exactly `unmapped` (a status the vocabulary does not know) or a missing status. Everything
    the system deliberately recorded, including the non-REJECTED terminal families
    (DROPPED_*, SKIPPED_*, QUEUE_FULL, PLACEMENT_FAILED, TIMEOUT) and the in-flight ones, is
    accounted for.

    The old test counted only `"REJECTED" in status`, which reported 2,688 explicitly-
    dispositioned signals as silently dead. Defining it this way also makes the number a real
    schema-drift alarm rather than a noise figure: it can only be non-zero if a status appears
    that this module does not know about.
    """
    if not (status or "").strip():
        return False
    return bucket(status) != "unmapped"


def is_dedup_duplicate(status: Optional[str]) -> bool:
    """The dedup disposition ONLY (status == DUPLICATE).

    Deliberately NOT a substring test: `REJECTED_DUPLICATE_SYMBOL` also contains "DUPLICATE"
    but is a different thing -- an active position already exists on that symbol. The old
    `"DUPLICATE" not in status` test conflated the two.
    """
    return (status or "").upper() == "DUPLICATE"


def is_sizing_rejection(status: Optional[str]) -> bool:
    """True for the position_sizer's REJECTED_SIZING_* family -- 'capital/sizing refused it'.

    Excludes REJECTED_SIZING_VALID, which is the risk engine's check-2 name, not a
    position_sizer constraint (see _RISK_ENGINE_SIZING_STATUS)."""
    s = (status or "").upper()
    if s == _RISK_ENGINE_SIZING_STATUS:
        return False
    return s.startswith(SIZING_PREFIX)


def sizing_constraint(status: Optional[str]) -> Optional[str]:
    """Which sizing guard bound, e.g. 'CONCENTRATION' / 'CAPITAL' / 'ZERO_MULTIPLIER'.
    None when the status is not a position_sizer sizing rejection -- including the risk
    engine's REJECTED_SIZING_VALID, which is not a sizer constraint (it would otherwise
    report a bogus constraint 'VALID')."""
    s = (status or "").upper()
    if s == _RISK_ENGINE_SIZING_STATUS or not s.startswith(SIZING_PREFIX):
        return None
    return s[len(SIZING_PREFIX):] or None


def family(status: Optional[str]) -> str:
    """The status collapsed to its reporting family -- what a breakdown should GROUP BY.

    Identity for every status except the per-score rejections, which collapse to
    REJECTED_SCORE. Grouping by this turned a 190-line breakdown into 9 on real data.
    """
    s = (status or "").upper() or "UNKNOWN"
    if _SCORE_STATUS_RE.match(s):
        return "REJECTED_SCORE"
    return s
